export const CHANGE_PAGE_TITLE='CHANGE_PAGE_TITLE';
export const ADD_CART='ADD_CART';
export const TOGGLE_PAGE_STATUS='TOGGLE_PAGE_STATUS';
export const INCRESE_CART_COUNT='INCRESE_CART_COUNT';
export const DECRESE_CART_COUNT='DECRESE_CART_COUNT';
export const TOGGLE_CART_STATUS='TOGGLE_CART_STATUS';
export const TOGGLE_ALL_CART_STATUS='TOGGLE_ALL_CART_STATUS';
export const DELETE_CART_ISCHECKED='DELETE_CART_ISCHECKED';
export const TOGGLE_CART_EIDT='TOGGLE_CART_EIDT';
export const TOGGLE_LOGIN_STATUS='TOGGLE_LOGIN_STATUS';







